BiDoner/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiDoner.Controllers
{
    public class AboutUsController : Controller
    {
        [Route("Hakkimizda")]
        public ActionResult Hakkimizda()
        {
            ViewBag.Current = "Hakkimizda";
            return View();
        }

    }
}

BiDoner/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiDoner.Controllers
{
    public class ContactController : Controller
    {
        [Route("İletisim")]
        public ActionResult Iletisim()
        {
            ViewBag.Current = "Iletisim";
            return View();
        }
    }
}

BiDoner/Controllers/MenuController.cs
using BiDoner.DAL.Concrete;
using BiDoner.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BiDoner.Controllers
{
    public class MenuController : Controller
    {
        [Route("Menu")]
        public ActionResult Menu()
        {
            ProductDAL proMng = new ProductDAL();
            CategoryDAL catDal = new CategoryDAL();

            var productList = proMng.GetActiveProducts();
            var categoryList = catDal.GetAllActiveCategories();
            ViewData["Current"] = "Menu";
            GeneralMenuModel generalModel = new GeneralMenuModel();

            generalModel.ProductList = productList;
            generalModel.CategoryList = categoryList;

            return View(generalModel);
        }
    }
}

BiDoner/Views/Shared/_Footer.cshtml
    <!-- BEGIN FOOTER -->
<footer id="footer" class="section" role="contentinfo">
    <div class="container">
        <ul class="social">
            <li><a href="https://www.instagram.com/bikoftebidoner/" class="icon ig"><i class="fa fa-instagram"></i></a></li>
            <li><a href="https://www.facebook.com/bikoftebidoner/" class="icon fb"><i class="fa fa-facebook"></i></a></li>
            @*<li><a href="#" class="icon in"><i class="fa fa-pinterest"></i></a></li>
                 <li><a href="#" class="icon go"><i class="fa fa-google-plus"></i></a></li>*@
        </ul>
    </div>
</footer>
<!-- END FOOTER -->

BiDoner/Views/Shared/_Header.cshtml
    <!-- BEGIN HEADER -->
<header id="header" role="banner">
    <div class="jt_row container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand normal logo" href="#"><div class="logo_elixir"></div></a>
            <a class="navbar-brand mini" href="#"><div class="logo_elixir dark"></div></a>
            <a class="navbar-brand mini darker" href="#"><div class="logo_elixir dark"></div></a>
        </div>
        <!-- BEGIN NAVIGATION MENU-->
        <nav class="collapse navbar-collapse navbar-right navbar-main-collapse" role="navigation">
            <ul id="nav" class="nav navbar-nav navigation">
                <li class="page-scroll menu-item"><a href="@Url.Action("Anasayfa","Home")">Anasayfa</a></li>
                <li class="page-scroll menu-item"><a href="@Url.Action("Hakkimizda", "AboutUs")">Hakkımızda</a></li>
                <li class="page-scroll menu-item"><a href="@Url.Action("Menu","Menu")">Menu</a></li>
                @*<li class="page-scroll menu-item"><a href="@Url.Action("Gallery","Gallery")">Galleri</a></li>*@
                <li class="page-scroll menu-item"><a href="@Url.Action("Iletisim","Contact")">İletişim</a></li>
              
            </ul>
        </nav>
        <!-- EN NAVIGATION MENU -->
    </div>
</header>
<!-- END HEADER -->

BiDoner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bi Döner && Bi Köfte</title>
    <!-- GOOGLE FONTS -->
    <link href='http://fonts.googleapis.com/css?family=Yellowtail%7cCabin:400,500,600,700,400italic,700italic%7cLibre+Baskerville:400italic%7cGreat+Vibes%7cOswald:400,300,700%7cOpen+Sans:600italic,700' rel='stylesheet' type='text/css'>
    <!-- META TAGS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="robots" content="index, follow" />
    <!-- CSS STYLESHEETS -->
    
    <link rel="shortcut icon" href="~/Content/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/images/favicon.ico" type="image/x-icon">


    @RenderSection("CustomPageCss", required: false)


    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/css/elixir.css" rel="stylesheet" />
    <link href="~/Content/css/YTPlayer.css" rel="stylesheet" />
    <link href="~/Scripts/owl-carousel/owl.carousel.css" rel="stylesheet" />
    <link href="~/Scripts/owl-carousel/owl.theme.css" rel="stylesheet" />
    <link href="~/Scripts/owl-carousel/owl.transitions.css" rel="stylesheet" />
</head>


<body>

    <div id="mask">
        <div class="loader">
            <img src="~/Content/svg-loaders/tail-spin.svg" alt='loading'>
        </div>
    </div>

        @Html.Partial("_Header")



    @RenderBody()


    @Html.Partial("_Footer")


    <a href="#0" class="cd-top">Top</a>
    <!-- BEGIN Scripts-->

    @RenderSection("CustomPageJs", required: false)


    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/modernizr.custom.js"></script>
    <script src="~/Scripts/classie.js"></script>
    <script src="~/Scripts/pathLoader.js"></script>
    <script src="~/Scripts/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/Scripts/jquery.inview.js"></script>
    <script src="~/Scripts/jquery.nav.js"></script>
    <script src="~/Scripts/jquery.mb.YTPlayer.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/default.js"></script>
    <script src="~/Scripts/plugins.js"></script>
    <script src="~/Scripts/jquery.isotope.min.js"></script>
    <script src="~/Scripts/jquery.prettyPhoto.js"></script>
    <script src="~/Scripts/jquery.swipebox.js"></script>


    <script>
        $(document).ready(function () {
            // get current URL path and assign 'active' class

            var pathname = window.location.pathname;
            $('#nav > li > a[href="' + pathname + '"]').parent().addClass('current');
        })
    </script>

    <script type="text/javascript">
    ;( function( $ ) {

        $( '.swipebox' ).swipebox();

    } )( jQuery );
    </script>

    <!-- END Scripts -->
</body>
</html>

BiDoner/Views/Shared/_Slider.cshtml
    <!-- BEGIN HOME SLIDER SECTION -->
<section id="home-slider">
    <div class="overlay"></div>
    <!-- SLIDER IMAGES -->
    <div id="owl-main" class="owl-carousel">
        <div class="item"><img src="~/Content/images/slider/2489x1300 görsel d.png" alt="Slide 03"></div>
        <div class="item"><img src="~/Content/images/slider/2489x1300 görsel b.png" alt="Slide 01"></div>
        <div class="item"><img src="~/Content/images/slider/2489x1300 görsel c.png" alt="Slide 02"></div>
        
        @*<div class="item"><img src="http://www.oburger.com.tr/images/back/3.jpg" alt="Slide 04"></div>*@
    </div>
    
    <!-- SLIDER CONTENT -->
    @*<div class="slide-content">
        <div class="voffset100"></div>
        <span class="logointro"></span>
        <div id="owl-main-text" class="owl-carousel">
            <div class="item">
                <h2>Türk Mutfağının Eşsiz Lezzetleri</h2>
            </div>
            <div class="item">
                <h2>Bi Döner && Bi Köfte</h2>
            </div>
            <div class="item">
                <h2>Lezzet Şölenine Hoşgeldiniz</h2>
            </div>
        </div>
        <div class="slide-sep"></div>
        <p>Usta Şeflerimizin Yıllardır Süregelen Tecrübesi</p>

    </div>*@
    <!-- BOTTOM ANIMATED ARROW -->
    <a href="#menu" class="page-scroll menu-item"><div class="mouse"><span></span></div></a>
</section>
<!-- END HOME SLIDER SECTION -->

BiDoner/Views/Shared/_TopHeader.cshtml
<div class="header-top-bar-container clearfix">
    <div class="header-top-bar">
        <ul class="contact-details clearfix">
            <li class="template-phone">
                <a href="tel:+902422279663">0 (242) 227 9663</a>
            </li>
            <li class="template-mail">
                <a href="mailto:info@carzone.com.tr">info@carzone.com.tr</a>
            </li>

        </ul>
        <ul class="social-icons">
            <li>
                <a target="_blank" href="https://www.facebook.com/carzoneservis" class="social-facebook" title="facebook"></a>
            </li>
            <li>
                <a target="_blank" href="https://www.instagram.com/carzoneservice/" class="social-instagram" title="pinterest"></a>
            </li>
        </ul>
    </div>
    <a href="#" class="header-toggle template-arrow-up"></a>
</div>